---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: bento/ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[lamp_stack::default]
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:


  - name: jenkins
    run_list:
      - recipe[lamp_stack::jenkins]
    verifier:
      inspec_tests:
        - test/integration/jenkins
    attributes: